In [ ]:
#Import Libraries
import pandas as pd
import numpy as np

In [ ]:
#Read Data using panda
df = pd.read_csv('fifa21 raw data v2.csv',low_memory = False)

In [ ]:
#check data 
df.shape

(18979, 77)

In [ ]:
#check the Null Data
df.isnull()

ID   Name  LongName  photoUrl  playerUrl  Nationality    Age   ↓OVA  \
0      False  False     False     False      False        False  False  False   
1      False  False     False     False      False        False  False  False   
2      False  False     False     False      False        False  False  False   
3      False  False     False     False      False        False  False  False   
4      False  False     False     False      False        False  False  False   
...      ...    ...       ...       ...        ...          ...    ...    ...   
18974  False  False     False     False      False        False  False  False   
18975  False  False     False     False      False        False  False  False   
18976  False  False     False     False      False        False  False  False   
18977  False  False     False     False      False        False  False  False   
18978  False  False     False     False      False        False  False  False   

         POT   Club  ...    A/W    D/W     IR    PAC    SHO    PAS    DRI  \
0      False  False  ...  False  False  False  False  False  False  False   
1      False  False  ...  False  False  False  False  False  False  False   
2      False  False  ...  False  False  False  False  False  False  False   
3      False  False  ...  False  False  False  False  False  False  False   
4      False  False  ...  False  False  False  False  False  False  False   
...      ...    ...  ...    ...    ...    ...    ...    ...    ...    ...   
18974  False  False  ...  False  False  False  False  False  False  False   
18975  False  False  ...  False  False  False  False  False  False  False   
18976  False  False  ...  False  False  False  False  False  False  False   
18977  False  False  ...  False  False  False  False  False  False  False   
18978  False  False  ...  False  False  False  False  False  False  False   

         DEF    PHY   Hits  
0      False  False  False  
1      False  False  False  
2      False  False  False  
3      False  False  False  
4      False  False  False  
...      ...    ...    ...  
18974  False  False   True  
18975  False  False   True  
18976  False  False   True  
18977  False  False   True  
18978  False  False   True  

[18979 rows x 77 columns]

In [ ]:
#Remove Duplicates
df.drop_duplicates(inplace = True)

In [ ]:
#Drop the columns that we don't Need
df.drop(['ID','Name', 'photoUrl', 'playerUrl','Loan Date End'], axis = 1, inplace = True)

In [ ]:
#Rename the Columns
df.rename(columns={'↓OVA': 'OVA', 'LongName': 'Name'}, inplace=True)

In [ ]:
#cleans the column "club"
df.Club = df.Club.str.strip('\n\n\n\n')

In [ ]:
#check the contract column
df.Contract.unique()

array(['Active', 'On Loan', 'Free'], dtype=object)

In [ ]:
#change contract column 
def Contract_val(a):
    if "On Loan" in a:
        a = 'On Loan'
        return a
    elif '~' in a:
        a = 'Active'
        return a
    elif 'Free' in a:
        a = "Free"
        return a

In [ ]:
df.Contract = df.Contract.apply(Contract_val)

In [ ]:
df['Height'].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 201,
       158, 162, 161, 160, 203, 157, 156, 202, 159, 206, 155], dtype=int64)

In [ ]:
def convert_height(x):
    if x[-1] == '"':
        x = x.replace("\"","")
        inch = int(x[2:]) * 2.54
        foot = int(x[0]) * 30.48
        return round(foot+inch)
    elif x[-1] == "m":
        return int(x[:-2])

In [ ]:
df['Height'] = df['Height'].apply(convert_height)

In [ ]:
df['Weight'].unique()

array([72, 83, 87, 70, 68, 80, 71, 91, 73, 85, 92, 69, 84, 96, 81, 82, 75,
       86, 89, 74, 76, 64, 78, 90, 66, 60, 94, 79, 67, 65, 59, 61, 93, 88,
       97, 77, 62, 63, 95, 100, 58, '83', '81', '78', '88', '79', '77',
       '92', '76', '73', '66', '58', '86', '67', '74', '72', '87', '82',
       '63', '69', '71', 98, 103, 99, 102, 56, 101, 57, 55, 104, 107, 110,
       53, 50, 54, 52], dtype=object)

In [ ]:
def convert_weight(x):
    if 'lbs' in x:
        weight_lbs = float(x.strip('lbs'))
        weight_kg = int(weight_lbs * 0.45359237)
        return str(weight_kg)
    else:
        return int(x[:-2])

In [ ]:
df['Weight'] = df['Weight'].apply(convert_weight)

In [ ]:
#changes the column Preferred Foot
print(df["Preferred Foot"].unique())
df["Preferred Foot"] = np.where(df["Preferred Foot"]=="Right", "R", "L")

['Left' 'Right']


In [ ]:
#Rename the Columns
df.rename(columns={'Height': 'Height(cm)', 'Weight(cm)': 'Weight(kg)'}, inplace=True)

In [ ]:
df['Joined'] = pd.to_datetime(df['Joined'])

In [ ]:
df.Value.unique()

array([103500000,  63000000, 120000000, 129000000, 132000000, 111000000,
       120500000, 102000000, 185500000, 110000000, 113000000,  90500000,
        82000000,  17500000,  83500000,  33500000, 114500000,  78000000,
       103000000, 109000000,  92000000,  10000000,  76500000,  89500000,
        87500000,  79500000, 124000000, 114000000,  95000000,  92500000,
       105500000,  88500000,  85000000,  81500000,  26000000,  21000000,
        56000000,  67500000,  53000000,  36500000,  51000000,  65500000,
        46500000,  61500000,  72500000,  77500000,  43500000,  32500000,
        36000000,  32000000,  54000000,  49500000,  57000000,  66500000,
        74500000,  71500000, 121000000,  99000000,  67000000,  86500000,
        93500000,  70000000,  62000000,  66000000,  58000000,  44000000,
        81000000,  37000000,  14500000,  46000000,  47500000,  52500000,
        54500000,  34500000,  57500000,  51500000,  44500000,  55000000,
        48000000,  60500000,  63500000,  61000000, 

In [ ]:
def Value_to_numeric(x):
    if 'K' in x:
        x = x.replace('€','').replace('K','')
        x = float(x) * 1000
        return int(x)
    else:
        x = x.replace('€','').replace('M','')
        x = float(x) * 1000000
        return int(x)

df['Value'] = df['Value'].apply(Value_to_numeric)

In [ ]:
df.Wage.unique()

array([   560000,    220000,    125000,    370000,    270000,    240000,
          250000,    160000,    260000,    210000,    310000,    130000,
          350000,    300000,    190000,    145000,    195000,    100000,
          140000,    290000,     82000,    110000,    230000,    155000,
          200000,    165000,     95000,    170000,    105000,    115000,
          150000,    135000,     55000,     58000,     81000,     34000,
          120000,     59000,     90000,     65000,     56000,     71000,
           18000,     75000,     47000,     20000,     84000,     86000,
           74000,     78000,     27000,     68000,     85000,     25000,
           46000,     83000,     54000,     79000,    175000,     43000,
           49000,     45000,     38000,     41000,     39000,     23000,
           51000,     50000,     87000,     30000,     14000,     69000,
           31000,     64000,     53000,     35000,     21000,     28000,
           17000,     33000,     70000,     32000, 

In [ ]:
def wage_to_numeric(x):
    if 'K' in x:
        x = x.replace('€','').replace('K','')
        x = float(x) * 1000
        return int(x)
    else:
        x = x.replace('€','').replace('M','')
        x = float(x) * 1000000
        return int(x)

df['Wage'] = df['Wage'].apply(wage_to_numeric)


In [ ]:
df['Release Clause'].unique()

array([138400000,  75900000, 159400000, ...,     59000,     35000,
           64000], dtype=int64)

In [ ]:
def Release_to_numeric(x):
    if 'K' in x:
        x = x.replace('€','').replace('K','')
        x = float(x) * 1000
        return int(x)
    else:
        x = x.replace('€','').replace('M','')
        x = float(x) * 1000000
        return int(x)

df['Release Clause'] = df['Release Clause'].apply(Release_to_numeric)

In [ ]:
df[['W/F', 'SM', 'IR']] = df[['W/F', 'SM', 'IR']].replace('★', '', regex=True).astype(int)
df["Age"] = df["Age"].astype(int)

In [ ]:
df.Hits.unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', 1600,
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', 1100, '433', '242', '206', '177', 1500, '198', '459', '117',
       '119', '209', '84', '187', '165', '203', '65', '336', '126', '313',
       '124', '145', '538', '182', '101', '45', '377', '99', '194', '403',
       '414', '593', '374', '245', 3200, '266', '299', '309', '215',
       '265', '211', '112', '337', '70', '159', '688', '116', '63', '144',
       '123', '71', '224', '113', '168', '61', '89', '137', '278', '75',
       '148', '176', '197', '264', '214', '247', '402', '440', 1700, 2300,
       '171', '320', '657', '87', '259', '200', '255', '253', '196', '60',
       '97', '85', '169', '256', '132', '239', '166', '121', '109', '32',
       '46', '122', '48', '527', '199', '282', '51', 1900, '642', '155',
       '323', '288', '497', '509', '79', '49', '270', 

In [ ]:
def hitchange(h):
    if isinstance(h, float):
        return h
    elif "K" in h:
        h = h.replace('K', "")
        h = float(h) * 1000
        return round(h)
    else:
        return h
df['Hits'] = df['Hits'].apply(hitchange)

In [ ]:
df['Hits'] = df['Hits'].fillna(0)

In [ ]:
#A view at Dataset
pd.set_option('display.max_columns', 77)
df.head(10)

Name Nationality  Age  OVA  POT  \
0                  Lionel Messi   Argentina   33   93   93   
1  C. Ronaldo dos Santos Aveiro    Portugal   35   92   92   
2                     Jan Oblak    Slovenia   27   91   93   
3               Kevin De Bruyne     Belgium   29   91   91   
4    Neymar da Silva Santos Jr.      Brazil   28   91   91   
5            Robert Lewandowski      Poland   31   91   91   
6                 Mohamed Salah       Egypt   28   90   90   
7         Alisson Ramses Becker      Brazil   27   90   91   
8                 Kylian Mbappé      France   21   90   95   
9         Marc-André ter Stegen     Germany   28   90   93   

                  Club Contract   Positions  Height(cm) Weight(kg)  \
0         FC Barcelona   Active  RW, ST, CF         170         72   
1             Juventus   Active      ST, LW         187         83   
2      Atlético Madrid   Active          GK         188         87   
3      Manchester City   Active     CAM, CM         181         70   
4  Paris Saint-Germain   Active     LW, CAM         175         68   
5    FC Bayern München   Active          ST         184         80   
6            Liverpool   Active          RW         175         71   
7            Liverpool   Active          GK         191         91   
8  Paris Saint-Germain   Active  ST, LW, RW         178         73   
9         FC Barcelona   Active          GK         187         85   

  Preferred Foot  BOV Best Position     Joined      Value    Wage  \
0              L   93            RW 2004-07-01  103500000  560000   
1              R   92            ST 2018-07-10   63000000  220000   
2              R   91            GK 2014-07-16  120000000  125000   
3              R   91           CAM 2015-08-30  129000000  370000   
4              R   91            LW 2017-08-03  132000000  270000   
5              R   91            ST 2014-07-01  111000000  240000   
6              L   90            RW 2017-07-01  120500000  250000   
7              R   90            GK 2018-07-19  102000000  160000   
8              R   91            ST 2018-07-01  185500000  160000   
9              R   90            GK 2014-07-01  110000000  260000   

   Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
0       138400000        429        85         95                70   
1        75900000        437        84         95                90   
2       159400000         95        13         11                15   
3       161000000        407        94         82                55   
4       166500000        408        85         87                62   
5       132000000        423        71         94                85   
6       144300000        392        79         91                59   
7       120300000        114        17         13                19   
8       203100000        408        78         91                73   
9       147700000        118        18         14                11   

   Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  Long Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   
4             87       87    448         95     88           89            81   
5             84       89    407         85     79           85            70   
6             84       79    406         90     83           69            75   
7             45       20    138         27     19           18            44   
8             83       83    394         92     79           63            70   
9             61       14    144         21     18           12            63   

   Ball Control  Movement  Acceleration  Sprint Speed  Agility  Reactions  \
0            96       451            91            80       91

In [ ]:
df.to_excel('fifa_cleaned_data.xlsx', index=False)